# Generated by Django 4.0.1 on 2022-08-22 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_user_todo_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('-created_at',), 'verbose_name': 'My Todo', 'verbose_name_plural': 'My Todos'},
        ),
    ]
